language: python
python:
  - "3.6"
install:
  - pip3 install colored
  - pip3 install coveralls
script: 
  - coverage run -m unittest test_rpn.py
after_success:
  coveralls

#script: - python3 -m unittest